#!/bin/sh
# {{@@ header() @@}}

# ~/.bash_profile_public
# This file is sourced by ~/.bash_profile and contains commands that can be safely shared publicly.

export PS1_CHAR="${PS1_CHAR:-χ}"
export DOTDROP_PROFILE="${DOTDROP_PROFILE:-'debian'}"

{%@@ if exists('$HOME/.cargo/bin') @@%}
export PATH="$HOME/.cargo/bin:$PATH"
{%@@ endif @@%}

# source .bashrc if using bash
# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
    fi
fi

{%@@ if exists_in_path('batcat') or exists_in_path('bat') @@%}
# colorize man pages
# from <https://www.vimfromscratch.com/articles/awesome-command-line-tools/>
export MANPAGER="sh -c 'col -bx | batcat -l man -p'"
{%@@ endif @@%}

{%@@ if exists_in_path('pandoc') @@%}
eval "$(pandoc --bash-completion)"
{%@@ endif @@%}

{%@@ if exists('$HOME/.tmux/plugins/tpm') @@%}
export TMUX_PLUGIN_MANAGER_PATH="~/.tmux/plugins/tpm"
{%@@ endif @@%}
