#!/bin/sh
# {{@@ header() @@}}

# alias ls command
alias ls="ls --all -l --human-readable --group-directories-first --color"
# alias printenv for environment variables
alias printenv="printenv | sed '/.:./ { s/:/\n\t/g; }'"

{%@@ if exists_in_path('pandoc') @@%}
# alias pandoc to point to version installed for entire system
# otherwise, anaconda version will come first in $PATH
alias pandoc="/usr/bin/pandoc"
{%@@ endif @@%}

{%@@ if env['CONDA_EXE'] is defined @@%}
# python/notebook aliases
# create command for referencing the system's "default" jupyter installation
alias jupyd="$CONDA_EXE run -n jupyter_server jupyter"
{%@@ endif @@%}

{%@@ if exists_in_path('diff-so-fancy') @@%}
# improved diff command
alias diff="diff-so-fancy"
{%@@ endif @@%}

{%@@ if exists_in_path('bat') @@%}
# improved cat
alias cat="bat"
{%@@ elif exists_in_path('batcat') @@%}
alias cat="batcat"
{%@@ endif @@%}

{%@@ if exists_in_path('exa') @@%}
# improved 'ls'
alias l="exa -lahF"
{%@@ endif @@%}

# improved 'find'
{%@@ if exists_in_path('fd') @@%}
alias find="fd"
{%@@ else @@%}
alias fd="find"
{%@@ endif @@%}

# change "z" command to "j"
export _Z_CMD="j"

# dotdrop
alias dotdrop="{{@@ env['HOME'] @@}}/dotfiles/dotdrop.sh --profile={{@@ env['DOTDROP_PROFILE'] @@}} --cfg={{@@ env['HOME'] @@}}/dotfiles/config.yaml"

# archive box
{%@@ if exists_in_path('archivebox') @@%}
alias archivebox='env OUTPUT_DIR="{{@@ env['HOME'] @@}}/Documents/archivebox" MEDIA_TIMEOUT=120 archivebox'
{%@@ endif @@%}

{%@@ if exists_in_path('rsync') @@%}
alias copydir="rsync --verbose --archive --human-readable --compress --recursive --info=progress2"
alias copydir-update="copydir --update"
alias copydir-resume="copydir --append-verify"
alias copyfiles="rsync --verbose --archive --human-readable --compress --info=progress2"
{%@@ endif @@%}
