config:
  backup: true
  create: true
  dotpath: dotfiles
  link_dotfile_default: link
  import_actions:
  - setup/setup_actions.yaml
dotfiles:
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
    actions:
    - vim-plug-setup
  f_bash_aliases:
    src: bash_aliases
    dst: ~/.bash_aliases
  f_pylintrc:
    src: pylintrc
    dst: ~/.pylintrc
  f_condarc:
    src: condarc
    dst: ~/.condarc
  f_cookiecutterrc:
    src: cookiecutterrc
    dst: ~/.cookiecutterrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
    actions:
    - pip-setup
    - nbdime-vcs-setup
    - dsf-install
  d_git:
    src: git
    dst: ~/.git
  f_solarized.vim:
    src: vim/colors/solarized.vim
    dst: ~/.vim/colors/solarized.vim
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
    actions:
    - rust-install
    - cargo-setup
    - debian-setup
    - z-install
    - tmux-install
  f_jrnl.yaml:
    src: config/jrnl/jrnl.yaml
    dst: ~/.config/jrnl/jrnl.yaml
    link: nolink
    actions:
    - pip-setup
    - debian-setup
  f_direnvrc:
    src: direnvrc
    dst: ~/.direnvrc
    link: nolink
    actions:
    - debian-setup
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
    link: nolink
    actions:
    - tmux-install
    - tmux-tpm-setup
  f_bash_profile_public:
    src: bash_profile_public
    dst: ~/.bash_profile_public
    link: nolink
  f_config_flake8:
    src: config/flake8
    dst: ~/.config/flake8
    link: nolink
  f_pycodestyle:
    src: config/pycodestyle
    dst: ~/.config/pycodestyle
    link: nolink
  f_flake8:
    src: config/jupyterserver/flake8
    dst: ~/.config/jupyterserver/flake8
    link: nolink
  f_jupyterserver_pycodestyle:
    src: config/jupyterserver/pycodestyle
    dst: ~/.config/jupyterserver/pycodestyle
    link: nolink
  d_matplotlib:
    src: config/jupyterserver/matplotlib
    dst: ~/.config/jupyterserver/matplotlib
    link: nolink
  d_user-settings:
    src: config/jupyterserver/.jupyter/lab/user-settings
    dst: ~/.config/jupyterserver/.jupyter/lab/user-settings
    link: nolink
  f_custom.css:
    src: config/Zettlr/custom.css
    dst: ~/.config/Zettlr/custom.css
    link: nolink
  f_tags.json:
    src: config/Zettlr/tags.json
    dst: ~/.config/Zettlr/tags.json
    link: nolink
  f_user.dic:
    src: config/Zettlr/user.dic
    dst: ~/.config/Zettlr/user.dic
    link: nolink
profiles:
  debian:
    actions:
    - debian-setup
    - z-install
    dotfiles:
    - f_vimrc
    - f_bash_aliases
    - f_pylintrc
    - f_condarc
    - f_cookiecutterrc
    - f_gitconfig
    - d_git
    - f_solarized.vim
    - f_bashrc
    - f_jrnl.yaml
    - f_direnvrc
    - f_tmux.conf
    - f_bash_profile_public
    - f_config_flake8
    - f_pycodestyle
    - f_flake8
    - f_jupyterserver_pycodestyle
    - d_matplotlib
    - d_user-settings
    - f_custom.css
    - f_tags.json
    - f_user.dic
  debian_cuda:
    include:
    - debian

