actions:
  pre:
    debian-setup: mkdir --parents {{@@ env['HOME'] @@}}/bin && sudo apt update && xargs --arg-file="{{@@ env['HOME'] @@}}/dotfiles/setup/apt_pkglist" sudo apt -y install
    nbdime-install: pip install --upgrade --quiet nbdime
    dsf-install: wget https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy --output-document {{@@ env['HOME'] @@}}/bin/diff-so-fancy && chmod +x {{@@ env['HOME'] @@}}/bin/diff-so-fancy
    rust-install: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o {{@@ env['HOME'] @@}}/rustup.sh && sh {{@@ env['HOME'] @@}}/rustup.sh --quiet --no-modify-path -y && rm {{@@ env['HOME'] @@}}/rustup.sh && tail {{@@ env['HOME'] @@}}/.cargo/env #source {{@@ env['HOME'] @@}}/.cargo/env 
    z-install: wget https://raw.githubusercontent.com/rupa/z/master/z.sh --output-document {{@@ env['HOME'] @@}}/bin/z.sh && chmod +x {{@@ env['HOME'] @@}}/bin/z.sh
  post:
    nbdime-vcs-setup: nbdime config-git --enable --global
    vim-plug-setup: vim +PlugInstall +qall
config:
  backup: true
  create: true
  dotpath: dotfiles
  link_dotfile_default: link
dotfiles:
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
    actions:
      - vim-plug-setup
  f_bash_aliases:
    src: bash_aliases
    dst: ~/.bash_aliases
  f_pylintrc:
    src: pylintrc
    dst: ~/.pylintrc
  f_condarc:
    src: condarc
    dst: ~/.condarc
  f_cookiecutterrc:
    src: cookiecutterrc
    dst: ~/.cookiecutterrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
    actions:
      - nbdime-install
      - nbdime-vcs-setup
      - dsf-install
  d_git:
    src: git
    dst: ~/.git
  f_solarized.vim:
    src: vim/colors/solarized.vim
    dst: ~/.vim/colors/solarized.vim
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
profiles:
  debian:
    actions:
    - debian-setup
    - rust-install
    - z-install
    dotfiles:
    - f_vimrc
    - f_bash_aliases
    - f_pylintrc
    - f_condarc
    - f_cookiecutterrc
    - f_gitconfig
    - d_git
    - f_solarized.vim
    - f_bashrc
  debian_cuda:
    include:
    - debian

