actions:
  pre:
    debian-setup: mkdir ~/bin && sudo apt update && xargs --arg-file="setup/apt_pkglist" sudo apt -y install
    nbdime-install: pip install --upgrade --quiet nbdime
    dsf-install: wget https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy -o ~/bin/diff-so-fancy && chmod +x ~/bin/diff-so-fancy
  post:
    nbdime-vcs-setup: nbdime config-git --enable --global
    vim-plug-setup: vim +PlugInstall +qall
config:
  backup: true
  create: true
  dotpath: dotfiles
  link_dotfile_default: link
dotfiles:
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
    actions:
      - vim-plug-setup
  f_bash_aliases:
    src: bash_aliases
    dst: ~/.bash_aliases
  f_pylintrc:
    src: pylintrc
    dst: ~/.pylintrc
  f_condarc:
    src: condarc
    dst: ~/.condarc
  f_cookiecutterrc:
    src: cookiecutterrc
    dst: ~/.cookiecutterrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
    actions:
      - nbdime-install
      - nbdime-vcs-setup
      - dsf-install
  d_git:
    src: git
    dst: ~/.git
  f_solarized.vim:
    src: vim/colors/solarized.vim
    dst: ~/.vim/colors/solarized.vim
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
profiles:
  debian:
    actions:
    - debian-setup
    dotfiles:
    - f_vimrc
    - f_bash_aliases
    - f_pylintrc
    - f_condarc
    - f_cookiecutterrc
    - f_gitconfig
    - d_git
    - f_solarized.vim
    - f_bashrc
  debian_cuda:
    include:
    - debian

