# {{@@ header() @@}}

default_hour: 0
default_minute: 1
editor: 'vim'
encrypt: false
highlight: true
indent_character: '|'
journals:
  {%@@ if exists('$HOME/Projects/_weller_labwork') @@%}
  default: "{{@@ env['HOME'] @@}}/Projects/_weller_labwork/journal/journal.txt"
  {%@@ else @@%}
  default: "{{@@ env['HOME'] @@}}/Documents/jrnl/journal.txt"
  {%@@ endif @@%}
linewrap: 79
tagsymbols: '@'
template: false
timeformat: '%Y_%m_%d_%H:%M'
version: 2.1.1
