# Sane, default build and tooling requirements for python projects.
# See PEP 518 <https://www.python.org/dev/peps/pep-0518/> for more details.

[tool.black]
fast = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

